deviseを使った認証機能実装
t-kuzuma/fjord-books_app-2023 pull request #3
Opened 2023-06-05 08:31 UTC by t-kuzuma

2023-06-11 14:45 UTC, u1tnk requested changes

2023-06-11 14:45 UTC, u1tnk commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page(params[:page]).per(4)
4の部分は定数であれば定義した方が良い。共通ならconfigで設定する方法もある…などと書こうと思ったのですが、そもそも1ページ4は少なすぎると思いますのでテスト用でしょうか？

2023-06-11 14:45 UTC, u1tnk commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
autofocus/autocompleteは どういう役割でしょうか？

2023-06-13 02:10 UTC, t-kuzuma commented on app/views/devise/registrations/edit.html.erb
> +    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
- ページを読み込んだ時にフォーカスを当てる機能
- emaiに対する自動補完機能
以上の役割ですが、編集ページではログインページと違ってフォーカスを当てたり補完したりする必要はないと考えられるため、削除します。不要な機能でした…

2023-06-13 02:10 UTC, t-kuzuma commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page(params[:page]).per(4)
4にしていたのはテストでした。ユーザーを何人か作成してページングできていることを確認していました。

> 4の部分は定数であれば定義した方が良い。共通ならconfigで設定する方法もある…などと書こうと思ったのですが、

デフォルトの25で問題無いと思うので、一旦は`per(4)`を削除しました。

2023-06-13 16:37 UTC, u1tnk approved these changes

2023-06-14 06:22 UTC, merged